
[tool.black]
line-length = 119
target-version = ["py312","py313"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "-q"

[tool.ruff]
# === БАЗОВОЕ ===
line-length = 119
target-version = "py311"  # можно py310 / py312

# Что проверяем (flake8 + isort + pyupgrade)
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
]

# Что игнорируем
ignore = [
    "E203",  # конфликт с black
    "W503",  # конфликт с black
]

# Исключения
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "migrations",
]

# Игнор для конкретных файлов
[tool.ruff.per-file-ignores]
"*/migrations/*.py" = ["E501"]
"settings.py" = ["E501"]